# https://docs.docker.com/compose/gettingstarted
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "${PORT:-8000}:80"
    restart: unless-stopped
  backend:
    build:
      context: ./backend
    environment:
      # Provide your openrouter key
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    volumes:
      - ${DATA_DIR:-./data}:/app/data
      # Load the gameConfig used for human evaluation
      - ./data/participants/gameConfig.ts:/app/src/config/gameConfig.ts:ro
    command: pnpm start:server
    restart: unless-stopped
